//
//  Videos.swift
//  listingSwift
//
//  Created by manish on 30/05/21.
//

import SwiftUI


struct Video : Identifiable{
    let id = UUID()
    let imageName : String
    let title : String
    let description : String
    let viewCount : String
    let uploadDate : String
    let url : URL
}

struct VideoList {
    static let topten = [
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!),
        Video( imageName: "youtube", title: "How I learned SwiftUI - Design+Code Course Review", description: "I finally made the leap and decided to start learning SwiftUI. The very first step I took was to take MengTo of Design+Code's course. I was drawn to this course because the app was beautifully designed and looked like a ton of fun to make. With this course, you are getting sort of a 2 for 1 deal. Not only will you learn SwiftUI, but you'll get some great design tips as well since Meng is an amazing designer. ", viewCount: "28,681", uploadDate: "Oct 3, 2018", url: URL(string: "https://www.youtube.com/watch?v=i7o76KejmQE&t=342s")!)
    ]
    
}

